# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  unit-test:
    docker:
      - image: cimg/go:1.21.1
    resource_class: small
    steps:
      - checkout  
      - run:
          name: sync submodule
          command: git submodule sync --recursive
      - run:
          name: ls
          command: ls -la test
      - run:
          name: ls
          command: ls -la test/MaxMind-DB
      - run:
          name: unit test
          command: go test -v -coverprofile=cov.out -coverpkg=./
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - codecov/upload:
                file: cov.out

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - unit-test